name: CI Pipeline

# Trigger workflow on push to main/dev and pull requests to main/dev
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Only run for PRs
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install --legacy-peer-deps --silent
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Run database migrations
        run: npx prisma migrate deploy
      - name: Build Next.js app
        run: npm run build
      # Add test steps here if you have them