name: CI Pipeline

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    env:
      # Use real secrets for push events, dummy for PRs
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install --legacy-peer-deps --silent
      - name: Generate Prisma client
        run: npx prisma generate
      # Only run migrations for push events (not PRs)
      - name: Run database migrations
        if: github.event_name == 'push'
        run: npx prisma migrate deploy
      - name: Build Next.js app
        run: npm run build
      # Add test steps here if you have them
      - name: Run tests
        run: echo "No tests defined yet"